export const LottoNumberValidationError = {
    LACK_COUNT_OF_LOTTO_NUMBER:"LACK_COUNT_OF_LOTTO_NUMBER",
    NOT_INTEGER:"NOT_INTEGER",
    VALIDATION:"VALIDATION",
    DUPLICATION_NUMBER:"DUPLICATION_NUMBER"
}
Object.freeze(LottoNumberValidationError)